# Generated by Django 3.1.3 on 2023-06-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numeros', '0004_remove_numero_lanzamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='numero',
            name='lanzamiento',
            field=models.TextField(default=''),
        ),
    ]
